### ISSUE TITLE
[Request] Maven Package

### ISSUE THREAD

**Issue by Jocomol** [jmarxuach/BatchPDFSign#10]
A Maven package can be created every time a new version is created.

The feature is already included and just has to be activated.

https://github.com/jmarxuach/BatchPDFSign/blob/master/.github/workflows/maven-publish.yml

**Comment by jmarxuach** [comment]
How can I activate it ? . I thought, it would be triggered on release.

**Comment by Jocomol** [comment]
@jmarxuach Ive added and updted the files, but there is a error. I think you need to fix it as I don't have the settings permission.
https://github.community/t/workflow-error-action-not-allowed/16788

**Comment by Jocomol** [comment]
@jmarxuach I think the actions are broken

**Comment by jmarxuach** [comment]
Ok, changed to Enable local and third-party Actions for this repository

**Comment by Jocomol** [comment]
fixed with https://github.com/jmarxuach/BatchPDFSign/releases/tag/1.0.5.2
