### ISSUE TITLE
Does not sign, the error is displayed:  "PdfReader is not opened with owner password"  and last "Unknown PdfException."

### ISSUE THREAD

**Issue by fhuayta** [jmarxuach/BatchPDFSign#22]
## Does not sign, the error is displayed: "PdfReader is not opened with owner password"

And change line 71 from BatchPDFSign.java, the error responce is: "Unknown PdfException."

 
![Selección_687](https://user-images.githubusercontent.com/5939439/200667070-d0fc926f-0027-4beb-87d6-840367c4cc1b.png)

**Comment by jmarxuach** [comment]
try remove all - chars in your path and file names.  Command line  uses - for parameters.

**Comment by fhuayta** [comment]
El problema es con el servicio de sellado de tiempo. Seleccionar un servicio de la siguiente lista: 

http://timestamp.digicert.com
http://timestamp.globalsign.com/tsa/r6advanced1
http://rfc3161timestamp.globalsign.com/advanced
http://timestamp.sectigo.com
http://timestamp.apple.com/ts01
http://tsa.mesign.com
http://time.certum.pl
https://freetsa.org
http://timestamp.globalsign.com/scripts/timstamp.dll
http://timestamp.globalsign.com/?signature=sha2
http://timestamp.wosign.com
http://tsa.startssl.com/rfc3161
http://dse200.ncipher.com/TSS/HttpTspServer
http://zeitstempel.dfn.de
https://ca.signfiles.com/tsa/get.aspx
http://services.globaltrustfinder.com/adss/tsa
https://tsp.iaik.tugraz.at/tsp/TspRequest
http://timestamp.entrust.net/TSS/RFC3161sha2TS
http://tsa.starfieldtech.com/

more details: 
- https://gist.github.com/Manouchehri/fd754e402d98430243455713efada710
- https://github.com/jmarxuach/BatchPDFSign/issues/21

issue closed
