### ISSUE TITLE
[Request] Updating the About page

### ISSUE THREAD

**Issue by Jocomol** [jmarxuach/BatchPDFSign#9]
The About description of the project still mentions Version 1.0.0.zip which is long outdated.

I propose this:
CLI Command line tool to digital signature of PDF files with PKCS12 certificate. You can find the executable in the releases. 

Also adding tags would probably help other people find this project and I think it could be very useful to other people.
I propose the following tags:
- cli
- pdf
- signature
- java-8
- java

**Comment by Jocomol** [comment]
Nevermind on the tags, I just saw that they are added already

**Comment by jmarxuach** [comment]
Done !
